### ISSUE TITLE
Make Social Card for Dataset Info page

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry-app#10]

**Comment by blaiszik** [comment]
This is trickier than I thought. I tried to add this using Vue, but Facebook, Twitter, etc do not pick up the tags because they are rendered in the browser. The way around this is server side rendering, but it may take some effort.

**Comment by kjschmidt913** [comment]
hmm for now should we just make sure the generic preview for Foundry looks nice? Do we need to add anything for that?
