### ISSUE TITLE
Add Loading indicator / Resolve "cannot read type 'undefined'" error in console

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry-app#20]
This happens on the dataset info page. I think this happens because the browser is trying to load the html before the API call is complete. Look into putting a line in that waits to render html until we have data. We might want a loading indicator to appear while this happens

**Comment by kjschmidt913** [comment]
This has become a higher priority now that I have added the footer to every page.

When the html is waiting on the data to load, the footer is at the top of the page then jumps down when content is loaded. It's jarring for the user. Need a loading indicator.

**Comment by kjschmidt913** [comment]
Also need loading indicator for datasets page. There isn't a console error, but the footer is loaded first and then jumps down.

**Comment by blaiszik** [comment]
Could we fix this by having a container of fixed size (longer than the screen length) in the DOM by default and populate it with the content once it loads?

**Comment by kjschmidt913** [comment]
Yes we could! I thought the loading indicator would look fun 😄 But really we can do whatever would make waiting for the data less visually jarring for the user
