### ISSUE TITLE
Data Search Page - Filters/Search Functionality

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry-app#3]
Depending on how many datasets we have, the sidebar should perhaps be a filter instead of a search. What I mean by this is that by default, all the datasets will load on the dataset search page, and the user would use the side bar to display only the datasets that meet the criteria they set with the sidebar.

Put either the filter or search query functionality in place.

**Comment by kjschmidt913** [comment]
for right now, add a filter like: https://codepen.io/AndrewThian/pen/QdeOVa

**Comment by kjschmidt913** [comment]
tried the codepen out but having issues. need to update via documentation: https://vuejs.org/guide/extras/reactivity-in-depth.html#how-reactivity-works-in-vue

**Comment by kjschmidt913** [comment]
scrap the filter idea. edit the API call to use search query and tags

**Comment by kjschmidt913** [comment]
Line 73 in the `q` add and AND with search q

**Comment by WillEngler** [comment]
(from planning: considering this more general as task to evaluate foundry polish)

**Comment by kjschmidt913** [comment]
Should this be tabled until summer? Summer student could create search page Ben slacked me about:

Since Foundry datasets are a subset of MDF datasets, make one search page.

From Ben: The Foundry app you built would become the only search interface we support and would have 1 mode for MDF datasets, and 1 for Foundry. So it would probably live at a page like [search.materialsdatafacility.org](http://search.materialsdatafacility.org/) or something like that. We can think about that a bit. It would just be nice not to have to maintain 2 search front ends (just for MDF)

**Comment by kjschmidt913** [comment]
Closing this issue. Created a new story for what this one has evolved into: https://github.com/MLMI2-CSSI/foundry-app/issues/60
