### ISSUE TITLE
fix homepage scroll bar that has just appeared

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry-app#45]
<img width="571" alt="Screen Shot 2022-09-07 at 5 55 51 PM" src="https://user-images.githubusercontent.com/16869564/189005438-a7336ffb-d68d-4b14-9ace-ad0e63444f03.png">

This appeared randomly, without any code changes. Added `overflow-x-hidden` class to elements that hold the code snippet but it's not working

**Comment by Aadit-Ambadkar** [comment]
Looks like the bar is gone now.
