### ISSUE TITLE
Update Model Publishing Documentation

### ISSUE THREAD

**Issue by kjschmidt913** [MLMI2-CSSI/foundry-app#62]
With the container service integrated, we should revisit our model documentation:

- [ ] Actual documentation for model publishing and running
- [ ] Model publishing notebook
- [ ] Any sort of information about publishing models on the foundry website? (maybe we don't need this? Do we have stuff about publishing datasets? check.)

**Comment by ascourtas** [comment]
this is still blocked because the container service hasn't been integrated yet

**Comment by ascourtas** [comment]
container service integration released in DLHub SDK 2.0.0! unblocked

**Comment by ascourtas** [comment]
@kjschmidt913 can you clarify, is this just for model publishing information on the website itself?
